### ISSUE TITLE
Might be a dumb question

### ISSUE THREAD

**Issue by Megan-Kwan** [KevinAllenWiegand/TravelersScreenSaver#8]
Hi, 
I'm having trouble installing your screensaver. 
I followed the instructions you posted, but am having trouble finding the scr file.

**Comment by KevinAllenWiegand** [comment]
Did you download the ZIP located here:  https://github.com/KevinAllenWiegand/TravelersScreenSaver/releases/tag/4?

This only works with a PC, so if you're on a MAC, it won't work.

The SCR file is called "Travelers.scr", and if you sort the files by name, it should be the bottom file.

**Comment by Megan-Kwan** [comment]
Got it, thank you so much for the clarification!
