### ISSUE TITLE
You can select multiple monitors but there is no OK to keep the selection

### ISSUE THREAD

**Issue by maddog22maddog** [KevinAllenWiegand/TravelersScreenSaver#9]
Thank you for this wonderful project.  On my monitor + 2 monitor setup, it does give options to select ALL  or individual screens for the screensaver.   However there is no OK to keep that selection.  If this could be added, it would be great!

**Comment by KevinAllenWiegand** [comment]
The settings save automatically as you change them...there is no OK button necessary for it.

**Comment by maddog22maddog** [comment]
It must be an issue on my configuration then because it doesn't when I select a choice and press X.  I will try a reboot and see if that may fix things up.  Thank you.
